// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sidflsbgvjvejqzssjjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpZGZsc2Jndmp2ZWpxenNzamp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4OTE3NDEsImV4cCI6MjA2MDQ2Nzc0MX0.Ik7BxAw58QxMC6m9eEhdMyF1IMj7fUmENGiv79rx00s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);